version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
    - .env
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      #- /app/node_modules
    environment:
      - FLASK_DEBUG=1
    restart: unless-stopped
