version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile-flask
    env_file:
    - .env
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    environment:
      #- FLASK_ENV=development
      - FLASK_DEBUG=1

  tailwind-dev:
    build:
      context: .
      dockerfile: Dockerfile-tailwind
    volumes:
      - ./app:/app
    working_dir: /app
